### ISSUE TITLE
Unable to download complete dataset (google drive 404)

### ISSUE THREAD

**Issue by yodhcn** [kuku-sichuan/ComparisonDetector#7]
https://drive.google.com/drive/folders/1YzPkv6rHLNQXA6QmEUoCl9mWV9fQFsik
https://github.com/kuku-sichuan/ComparisonDetector/blob/100cf669a97a50923bedbcb2021dfc9f6ebdd698/README.md?plain=1#L41

**Comment by chen-xing1** [comment]
Have you downloaded successfully

**Comment by yodhcn** [comment]
> 

NO

**Comment by SnowMoon19** [comment]
Have you solved it? I can not download too

**Comment by hinatanvir** [comment]
Can someone please help me download teh data . This link is inaccessible.

**Comment by BruceInWAlDEN** [comment]
see new place: https://github.com/CVIU-CSU/ComparisonDetector
